version: '2'

services:
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=mybatis
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
    ports:
      - "3306:3306"
#    volumes:
#      - /home/user/db/mysql/init:/docker-entrypoint-initdb.d/:ro

  server:
    build: ./src
    ports:
      - "12345:12345"
    volumes:
      - ./src:/code
    depends_on:
      - db
