version: '2'

services:
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=EM_System
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
    ports:
      - "3306:3306"
    volumes:
      - ./src/EM_System/src/main/resources/EM_System_SQL.txt:/docker-entrypoint-initdb.d/initial_db.sql
      - data-volume=/var/lib/mysql/data

  server:
    build: ./src
    ports:
      - "12345:12345"
    volumes:
      - ./src:/code
    depends_on:
      - db
